---
services:
  aliddns:
    image: aliddnstoa:latest
    container_name: aliddnstoa
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    environment:
       - "ACCESSKEY_ID=<HIDE>" 
       - "ACCESSKEY_SECRET=<HIDE>"
       - "DOMAIN_TTL=60"
       - "DOMAIN_NAME=example.com"
       - "DDNS1_DOMAIN=dns1.example.com"
       - "DDNS2_DOMAIN=dns2.example.com"
       - "A_DOMAIN=a.dns.example.com"
       - "A_RecordId1=1234"
       - "A_RecordId2=1235"
    # 控制日志数量
    logging:
       driver: "json-file"
       options:
          max-size: "200k"
          mode: "non-blocking"
          max-file: "10"
          max-buffer-size: "1000"
    restart: always